apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bloc-node
  namespace: bloc
  labels:
    app: bloc-node
spec:
  selector:
    matchLabels:
      app: bloc-node
  namespaceSelector:
    matchNames:
      - bloc
  endpoints:
    - port: http
      path: /metrics
      interval: 2s
