package app

import (
	"sync"
	"time"

	"bloc-node/internal/app/ethdemo"
	"bloc-node/internal/app/inclusion"
	"btd/be"
	"btd/curves"
	"github.com/anthdm/hbbft"
)

const (
	clusterConfigVersion = "bloc-cluster-v2"
	nodeSecretVersion    = "bloc-node-secret-v1"

	defaultMaxProposalBytes               = 8 << 20
	defaultMaxEnvelopeBytes               = 16 << 20
	defaultMaxCombineAttemptsPerSubBatch  = 256
	absoluteMaxProposalBytes              = 32 << 20
	absoluteMaxEnvelopeBytes              = 64 << 20
	absoluteMaxCombineAttemptsPerSubBatch = 4096
	minimumEnvelopeHeadroomBytes          = 64 << 10
)

// ConfigFile is the public JSON configuration shared by all BLOC nodes in a
// cluster. Operator-local BTE shares and libp2p private keys live separately in
// NodeSecretConfig files.
type ConfigFile struct {
	Version      string           `json:"version"`
	ClusterID    string           `json:"cluster_id"`
	BMax         int              `json:"bmax"`
	N            int              `json:"n"`
	Threshold    int              `json:"threshold"`
	Slot         uint64           `json:"slot"`
	CRSFile      string           `json:"crs_file"`
	CRSSHA256    string           `json:"crs_sha256"`
	Nodes        []NodeConfig     `json:"nodes"`
	PublicKeyHex string           `json:"public_key_hex"`
	Blockspace   BlockspaceConfig `json:"blockspace,omitempty"`
	Provider     ProviderConfig   `json:"provider,omitempty"`
	Network      NetworkConfig    `json:"network,omitempty"`
	Limits       ResourceLimits   `json:"limits,omitempty"`
	CRSBytes     []byte           `json:"-"`
}

// ResourceLimits bounds attacker-influenced protocol memory and cryptographic
// work. Zero values are filled with the stable v2 defaults.
type ResourceLimits struct {
	MaxProposalBytes              int `json:"max_proposal_bytes,omitempty"`
	MaxEnvelopeBytes              int `json:"max_envelope_bytes,omitempty"`
	MaxCombineAttemptsPerSubBatch int `json:"max_combine_attempts_per_sub_batch,omitempty"`
	explicitZeroProposal          bool
	explicitZeroEnvelope          bool
	explicitZeroCombineAttempts   bool
}

func defaultResourceLimits() ResourceLimits {
	return ResourceLimits{
		MaxProposalBytes:              defaultMaxProposalBytes,
		MaxEnvelopeBytes:              defaultMaxEnvelopeBytes,
		MaxCombineAttemptsPerSubBatch: defaultMaxCombineAttemptsPerSubBatch,
	}
}

// NodeConfig describes one operator process. HTTPAddr exposes the local control
// API, while the P2P fields identify the operator on the libp2p network.
type NodeConfig struct {
	ID               uint64 `json:"id"`
	HTTPAddr         string `json:"http_addr"`
	HTTPListenAddr   string `json:"http_listen_addr,omitempty"`
	HTTPAdvertiseURL string `json:"http_advertise_url,omitempty"`
	P2PAddr          string `json:"p2p_addr,omitempty"`
	P2PListenAddr    string `json:"p2p_listen_addr,omitempty"`
	P2PAdvertiseAddr string `json:"p2p_advertise_addr,omitempty"`
	P2PPeerID        string `json:"p2p_peer_id,omitempty"`
}

// NodeSecretConfig is the operator-local material generated by the prototype
// trusted dealer. It must never be placed in the shared cluster config.
type NodeSecretConfig struct {
	Version           string `json:"version"`
	ClusterID         string `json:"cluster_id"`
	OperatorID        uint64 `json:"operator_id"`
	BTEShareScalarHex string `json:"bte_share_scalar_hex"`
	P2PPrivateKeyHex  string `json:"p2p_private_key_hex"`
}

// ProviderConfig selects where a node gets its local inclusion-list proposal.
type ProviderConfig struct {
	Mode       string `json:"mode,omitempty"`
	MempoolURL string `json:"mempool_url,omitempty"`
}

// NetworkConfig records the node-to-node transport schema. libp2p is the only
// supported operator transport.
type NetworkConfig struct {
	Mode string `json:"mode,omitempty"`
}

// WireEnvelope is the internal message envelope passed between BLOC nodes.
// Exactly one protocol payload field should be set for a given Kind.
type WireEnvelope struct {
	From   uint64
	To     uint64
	Direct bool
	Kind   string
	Slot   uint64
	ACS    *hbbft.SlotMessage
	Share  *WireShare
}

// WireShare is the transport-safe representation of a BTE decryption share.
// Batch and curve point fields are hex encoded for protobuf transport and
// readable JSON artifacts.
type WireShare struct {
	OperatorID int
	BatchIDHex string
	SubBatchID int
	PointHex   string
}

type BlockspaceConfig = inclusion.BlockspaceConfig
type EncryptedPlaceholder = inclusion.EncryptedPlaceholder
type InclusionList = inclusion.InclusionList
type AgreedInclusionSet = inclusion.AgreedInclusionSet
type MergedEncryptedSet = inclusion.MergedEncryptedSet

// MaterializedTransactionSet is the final slot artifact after the selected
// encrypted placeholders have been decrypted.
type MaterializedTransactionSet struct {
	Slot             uint64              `json:"slot"`
	AgreedSetHash    string              `json:"agreed_set_hash"`
	MergedSetHash    string              `json:"merged_set_hash"`
	SelectedGas      uint64              `json:"selected_gas"`
	EncryptedHashes  []string            `json:"encrypted_hashes"`
	PlaintextHashes  []string            `json:"plaintext_hashes"`
	EthereumTxHashes []string            `json:"ethereum_tx_hashes,omitempty"`
	EthereumTxs      []EthereumTxSummary `json:"ethereum_txs,omitempty"`
	PlaintextsHex    []string            `json:"plaintexts_hex"`
}

type EthereumTxSummary = ethdemo.Summary

// SubmitTxRequest is accepted by the prototype HTTP API. The raw transaction
// may be supplied as hex; the remaining fields are metadata used by the merge
// rule before the encrypted payload is decrypted and parsed.
type SubmitTxRequest struct {
	RawTx                 string `json:"raw_tx"`
	Gas                   uint64 `json:"gas,omitempty"`
	EffectiveFeePerGasWei string `json:"effective_fee_per_gas_wei,omitempty"`
	From                  string `json:"from,omitempty"`
	Nonce                 uint64 `json:"nonce,omitempty"`
	Kind                  string `json:"kind,omitempty"`
}

type slotPhase string

const (
	slotPrepared  slotPhase = "prepared"
	slotRunning   slotPhase = "running"
	slotCompleted slotPhase = "completed"
)

// slotState contains everything that must be fresh for an independent
// protocol sample. Node embeds the active state so the protocol path remains
// compact while the evaluator can atomically replace it between slots.
type slotState struct {
	mu                  sync.Mutex
	inputMu             sync.Mutex
	acsMu               sync.Mutex
	id                  uint64
	phase               slotPhase
	slot                *hbbft.SlotACS
	startOnce           sync.Once
	pending             []EncryptedPlaceholder
	seenPending         map[string]bool
	plan                be.BatchPlan
	material            MaterializedTransactionSet
	planned             bool
	shareGenerationDone bool
	combineInFlight     bool
	shareVersion        uint64
	shareCandidates     map[int]*operatorShareCandidates
	combineAttemptsLeft []int
	result              *Result
	metrics             Metrics
	metricTimes         metricTimes
}

type operatorShareCandidates struct {
	batchID  [32]byte
	batchSet bool
	shares   map[int]retainedShare
}

type retainedShare struct {
	value   be.DecryptionShare
	encoded []byte
}

// Node owns the per-process BLOC state for one operator.
type Node struct {
	cfg              ConfigFile
	self             NodeConfig
	nodeIDs          []uint64
	peers            map[uint64]NodeConfig
	cluster          *be.ClusterBTE
	secret           be.SecretShare
	p2pPrivateKeyHex string
	suite            curves.Suite
	transport        Transport
	faults           FaultConfig

	lifecycleMu    sync.RWMutex
	lastSlot       uint64
	completedSlots uint64
	failedSlots    uint64
	observability  *nodeMetrics
	*slotState
}

// metricTimes retains monotonic clock readings inside one node process. The
// corresponding Unix timestamps in Metrics are evidence fields only; latency
// calculations must use these values so wall-clock adjustments cannot skew a
// run.
type metricTimes struct {
	slotStart            time.Time
	proposalReady        time.Time
	acsDecision          time.Time
	acsOutputDecoded     time.Time
	agreedSetDone        time.Time
	mergeDone            time.Time
	ciphertextsDecoded   time.Time
	planDone             time.Time
	shareGenerationStart time.Time
	sharesDone           time.Time
	threshold            time.Time
	combineDone          time.Time
	materialized         time.Time
}

// Result is the stable JSON shape returned by /result and emitted by evaluator
// runs once a node has materialized a slot.
type Result struct {
	Slot         uint64                     `json:"slot"`
	NodeID       uint64                     `json:"node_id"`
	BatchID      string                     `json:"batch_id"`
	Ciphertexts  int                        `json:"ciphertexts"`
	Plaintexts   []string                   `json:"plaintexts_hex"`
	Materialized MaterializedTransactionSet `json:"materialized_transaction_set"`
	LatencyMS    int64                      `json:"latency_ms"`
	Metrics      Metrics                    `json:"metrics"`
}

// FaultConfig enables deterministic local fault injection for evaluator runs.
type FaultConfig struct {
	OmitProposal  bool
	WithholdShare bool
	CorruptShare  bool
	Delay         time.Duration
}

// Metrics records per-node slot timings and byte/message counters. Timestamps
// are Unix nanoseconds so evaluator output can be post-processed without access
// to process-local monotonic clocks.
type Metrics struct {
	SubmittedTxs                 int              `json:"submitted_txs"`
	SubmittedBytes               int              `json:"submitted_bytes"`
	ProposalTxs                  int              `json:"proposal_txs"`
	ProposalHash                 string           `json:"proposal_hash,omitempty"`
	AgreedLists                  int              `json:"agreed_lists"`
	AgreedSetHash                string           `json:"agreed_set_hash,omitempty"`
	AgreedCiphertexts            int              `json:"agreed_ciphertexts"`
	MergedSetHash                string           `json:"merged_set_hash,omitempty"`
	SelectedCiphertexts          int              `json:"selected_ciphertexts"`
	SkippedCiphertexts           int              `json:"skipped_ciphertexts"`
	SelectedGas                  uint64           `json:"selected_gas"`
	MaxDecryptedGas              uint64           `json:"max_decrypted_gas"`
	MaxDecryptedTxs              int              `json:"max_decrypted_txs"`
	SubBatches                   int              `json:"sub_batches"`
	SharesGenerated              int              `json:"shares_generated"`
	SharesAccepted               int              `json:"shares_accepted"`
	SharesRejected               int              `json:"shares_rejected"`
	ShareSubsetAttempts          int              `json:"share_subset_attempts"`
	CombineAttempts              int              `json:"combine_attempts"`
	SharesNeededPerSub           int              `json:"shares_needed_per_sub_batch"`
	OutboundMessages             map[string]int   `json:"outbound_messages"`
	InboundMessages              map[string]int   `json:"inbound_messages"`
	OutboundBytes                map[string]int64 `json:"outbound_bytes"`
	InboundBytes                 map[string]int64 `json:"inbound_bytes"`
	SlotStartUnixNano            int64            `json:"slot_start_unix_nano"`
	ProposalReadyUnixNano        int64            `json:"proposal_ready_unix_nano"`
	ACSDecisionUnixNano          int64            `json:"acs_decision_unix_nano"`
	PlanDoneUnixNano             int64            `json:"plan_done_unix_nano"`
	ShareGenerationStartUnixNano int64            `json:"share_generation_start_unix_nano"`
	SharesDoneUnixNano           int64            `json:"shares_done_unix_nano"`
	FirstShareUnixNano           int64            `json:"first_share_unix_nano"`
	ThresholdUnixNano            int64            `json:"threshold_unix_nano"`
	CombineDoneUnixNano          int64            `json:"combine_done_unix_nano"`
	MaterializedUnixNano         int64            `json:"materialized_unix_nano"`
	ProposalPreparationUS        int64            `json:"proposal_preparation_us"`
	ACSUS                        int64            `json:"acs_us"`
	MergePlanUS                  int64            `json:"merge_plan_us"`
	ACSOutputDecodeUS            int64            `json:"acs_output_decode_us"`
	AgreedSetUS                  int64            `json:"agreed_set_us"`
	MergeUS                      int64            `json:"merge_us"`
	CiphertextDecodeUS           int64            `json:"ciphertext_decode_us"`
	BatchPlanUS                  int64            `json:"batch_plan_us"`
	ShareGenerationUS            int64            `json:"share_generation_us"`
	ThresholdWaitUS              int64            `json:"threshold_wait_us"`
	CombineUS                    int64            `json:"combine_us"`
	MaterializationUS            int64            `json:"materialization_us"`
	CommitToPlaintextUS          int64            `json:"commit_to_plaintext_us"`
	TotalSlotUS                  int64            `json:"total_slot_us"`
	MetricsFinalized             bool             `json:"metrics_finalized"`
	ACSMS                        int64            `json:"acs_ms"`
	PlanMS                       int64            `json:"plan_ms"`
	ShareGenerationMS            int64            `json:"share_generation_ms"`
	CommitToPlaintextMS          int64            `json:"commit_to_plaintext_ms"`
	TotalSlotMS                  int64            `json:"total_slot_ms"`
}
