package app

import (
	"sync"
	"time"

	"bloc-node/internal/app/ethdemo"
	"bloc-node/internal/app/inclusion"
	"btd/be"
	"btd/curves"
	"github.com/anthdm/hbbft"
)

// ConfigFile is the JSON configuration shared by all BLOC nodes in a local
// cluster. It contains consensus membership, BTE public material, per-node
// secret shares, and prototype runtime knobs such as provider and network mode.
type ConfigFile struct {
	ClusterID    string           `json:"cluster_id"`
	BMax         int              `json:"bmax"`
	N            int              `json:"n"`
	Threshold    int              `json:"threshold"`
	Slot         uint64           `json:"slot"`
	CRSSeedHex   string           `json:"crs_seed_hex"`
	Nodes        []NodeConfig     `json:"nodes"`
	PublicKeyHex string           `json:"public_key_hex"`
	Shares       []ShareConfig    `json:"shares"`
	Blockspace   BlockspaceConfig `json:"blockspace,omitempty"`
	Provider     ProviderConfig   `json:"provider,omitempty"`
	Network      NetworkConfig    `json:"network,omitempty"`
}

// NodeConfig describes one operator process. ConsensusAddr is used by the
// compatibility TCP transport, HTTPAddr exposes the local control API, and the
// P2P fields identify the same operator when libp2p mode is enabled.
type NodeConfig struct {
	ID            uint64 `json:"id"`
	ConsensusAddr string `json:"consensus_addr"`
	HTTPAddr      string `json:"http_addr"`
	P2PAddr       string `json:"p2p_addr,omitempty"`
	P2PPeerID     string `json:"p2p_peer_id,omitempty"`
	P2PPrivKeyHex string `json:"p2p_private_key_hex,omitempty"`
}

// ShareConfig stores one threshold-encryption secret share generated by the
// trusted dealer path in gen-config.
type ShareConfig struct {
	OperatorID int    `json:"operator_id"`
	ScalarHex  string `json:"scalar_hex"`
}

// ProviderConfig selects where a node gets its local inclusion-list proposal.
type ProviderConfig struct {
	Mode       string `json:"mode,omitempty"`
	MempoolURL string `json:"mempool_url,omitempty"`
}

// NetworkConfig selects the node-to-node transport implementation.
type NetworkConfig struct {
	Mode string `json:"mode,omitempty"`
}

// WireEnvelope is the internal message envelope passed between BLOC nodes.
// Exactly one protocol payload field should be set for a given Kind.
type WireEnvelope struct {
	From   uint64
	To     uint64
	Direct bool
	Kind   string
	Slot   uint64
	ACS    *hbbft.SlotMessage
	Share  *WireShare
}

// WireShare is the transport-safe representation of a BTE decryption share.
// Batch and curve point fields are hex encoded so the structure can travel
// through gob, JSON logs, or future protobuf messages without extra framing.
type WireShare struct {
	OperatorID int
	BatchIDHex string
	SubBatchID int
	PointHex   string
}

type BlockspaceConfig = inclusion.BlockspaceConfig
type EncryptedPlaceholder = inclusion.EncryptedPlaceholder
type InclusionList = inclusion.InclusionList
type AgreedInclusionSet = inclusion.AgreedInclusionSet
type MergedEncryptedSet = inclusion.MergedEncryptedSet

// MaterializedTransactionSet is the final slot artifact after the selected
// encrypted placeholders have been decrypted.
type MaterializedTransactionSet struct {
	Slot             uint64              `json:"slot"`
	AgreedSetHash    string              `json:"agreed_set_hash"`
	MergedSetHash    string              `json:"merged_set_hash"`
	SelectedGas      uint64              `json:"selected_gas"`
	EncryptedHashes  []string            `json:"encrypted_hashes"`
	PlaintextHashes  []string            `json:"plaintext_hashes"`
	EthereumTxHashes []string            `json:"ethereum_tx_hashes,omitempty"`
	EthereumTxs      []EthereumTxSummary `json:"ethereum_txs,omitempty"`
	PlaintextsHex    []string            `json:"plaintexts_hex"`
}

type EthereumTxSummary = ethdemo.Summary

// SubmitTxRequest is accepted by the prototype HTTP API. The raw transaction
// may be supplied as hex; the remaining fields are metadata used by the merge
// rule before the encrypted payload is decrypted and parsed.
type SubmitTxRequest struct {
	RawTx                 string `json:"raw_tx"`
	Gas                   uint64 `json:"gas,omitempty"`
	EffectiveFeePerGasWei string `json:"effective_fee_per_gas_wei,omitempty"`
	From                  string `json:"from,omitempty"`
	Nonce                 uint64 `json:"nonce,omitempty"`
	Kind                  string `json:"kind,omitempty"`
}

// Node owns the per-process BLOC state for one operator.
type Node struct {
	cfg       ConfigFile
	self      NodeConfig
	nodeIDs   []uint64
	peers     map[uint64]NodeConfig
	slot      *hbbft.SlotACS
	cluster   *be.ClusterBTE
	secret    be.SecretShare
	suite     curves.Suite
	transport Transport
	startOnce sync.Once
	faults    FaultConfig

	mu          sync.Mutex
	pending     []EncryptedPlaceholder
	seenPending map[string]bool
	plan        be.BatchPlan
	material    MaterializedTransactionSet
	planned     bool
	shares      []be.DecryptionShare
	seenShares  map[string]bool
	result      *Result
	metrics     Metrics
}

// Result is the stable JSON shape returned by /result and emitted by evaluator
// runs once a node has materialized a slot.
type Result struct {
	Slot         uint64                     `json:"slot"`
	NodeID       uint64                     `json:"node_id"`
	BatchID      string                     `json:"batch_id"`
	Ciphertexts  int                        `json:"ciphertexts"`
	Plaintexts   []string                   `json:"plaintexts_hex"`
	Materialized MaterializedTransactionSet `json:"materialized_transaction_set"`
	LatencyMS    int64                      `json:"latency_ms"`
	Metrics      Metrics                    `json:"metrics"`
}

// FaultConfig enables deterministic local fault injection for evaluator runs.
type FaultConfig struct {
	OmitProposal  bool
	WithholdShare bool
	CorruptShare  bool
	Delay         time.Duration
}

// Metrics records per-node slot timings and byte/message counters. Timestamps
// are Unix nanoseconds so evaluator output can be post-processed without access
// to process-local monotonic clocks.
type Metrics struct {
	SubmittedTxs        int              `json:"submitted_txs"`
	SubmittedBytes      int              `json:"submitted_bytes"`
	ProposalTxs         int              `json:"proposal_txs"`
	ProposalHash        string           `json:"proposal_hash,omitempty"`
	AgreedLists         int              `json:"agreed_lists"`
	AgreedSetHash       string           `json:"agreed_set_hash,omitempty"`
	AgreedCiphertexts   int              `json:"agreed_ciphertexts"`
	MergedSetHash       string           `json:"merged_set_hash,omitempty"`
	SelectedCiphertexts int              `json:"selected_ciphertexts"`
	SkippedCiphertexts  int              `json:"skipped_ciphertexts"`
	SelectedGas         uint64           `json:"selected_gas"`
	MaxDecryptedGas     uint64           `json:"max_decrypted_gas"`
	MaxDecryptedTxs     int              `json:"max_decrypted_txs"`
	SubBatches          int              `json:"sub_batches"`
	SharesGenerated     int              `json:"shares_generated"`
	SharesAccepted      int              `json:"shares_accepted"`
	SharesNeededPerSub  int              `json:"shares_needed_per_sub_batch"`
	OutboundMessages    map[string]int   `json:"outbound_messages"`
	InboundMessages     map[string]int   `json:"inbound_messages"`
	OutboundBytes       map[string]int64 `json:"outbound_bytes"`
	InboundBytes        map[string]int64 `json:"inbound_bytes"`
	SlotStartUnixNano   int64            `json:"slot_start_unix_nano"`
	ACSDecisionUnixNano int64            `json:"acs_decision_unix_nano"`
	PlanDoneUnixNano    int64            `json:"plan_done_unix_nano"`
	SharesDoneUnixNano  int64            `json:"shares_done_unix_nano"`
	FirstShareUnixNano  int64            `json:"first_share_unix_nano"`
	ThresholdUnixNano   int64            `json:"threshold_unix_nano"`
	CombineDoneUnixNano int64            `json:"combine_done_unix_nano"`
	ACSMS               int64            `json:"acs_ms"`
	PlanMS              int64            `json:"plan_ms"`
	ShareGenerationMS   int64            `json:"share_generation_ms"`
	CommitToPlaintextMS int64            `json:"commit_to_plaintext_ms"`
	TotalSlotMS         int64            `json:"total_slot_ms"`
}
