// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/bloc/v1/messages.proto

package blocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	From    uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To      uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Direct  bool                   `protobuf:"varint,4,opt,name=direct,proto3" json:"direct,omitempty"`
	Kind    string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Slot    uint64                 `protobuf:"varint,6,opt,name=slot,proto3" json:"slot,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Acs
	//	*Envelope_Share
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Envelope) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Envelope) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

func (x *Envelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Envelope) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAcs() *SlotMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Acs); ok {
			return x.Acs
		}
	}
	return nil
}

func (x *Envelope) GetShare() *WireShare {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Share); ok {
			return x.Share
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Acs struct {
	Acs *SlotMessage `protobuf:"bytes,10,opt,name=acs,proto3,oneof"`
}

type Envelope_Share struct {
	Share *WireShare `protobuf:"bytes,11,opt,name=share,proto3,oneof"`
}

func (*Envelope_Acs) isEnvelope_Payload() {}

func (*Envelope_Share) isEnvelope_Payload() {}

type WireShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    uint64                 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	BatchIdHex    string                 `protobuf:"bytes,2,opt,name=batch_id_hex,json=batchIdHex,proto3" json:"batch_id_hex,omitempty"`
	SubBatchId    uint64                 `protobuf:"varint,3,opt,name=sub_batch_id,json=subBatchId,proto3" json:"sub_batch_id,omitempty"`
	PointHex      string                 `protobuf:"bytes,4,opt,name=point_hex,json=pointHex,proto3" json:"point_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireShare) Reset() {
	*x = WireShare{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireShare) ProtoMessage() {}

func (x *WireShare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireShare.ProtoReflect.Descriptor instead.
func (*WireShare) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *WireShare) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *WireShare) GetBatchIdHex() string {
	if x != nil {
		return x.BatchIdHex
	}
	return ""
}

func (x *WireShare) GetSubBatchId() uint64 {
	if x != nil {
		return x.SubBatchId
	}
	return 0
}

func (x *WireShare) GetPointHex() string {
	if x != nil {
		return x.PointHex
	}
	return ""
}

type SlotMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Payload       *ACSMessage            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotMessage) Reset() {
	*x = SlotMessage{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotMessage) ProtoMessage() {}

func (x *SlotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotMessage.ProtoReflect.Descriptor instead.
func (*SlotMessage) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SlotMessage) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotMessage) GetPayload() *ACSMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ACSMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProposerId uint64                 `protobuf:"varint,1,opt,name=proposer_id,json=proposerId,proto3" json:"proposer_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ACSMessage_Agreement
	//	*ACSMessage_Broadcast
	Payload       isACSMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACSMessage) Reset() {
	*x = ACSMessage{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACSMessage) ProtoMessage() {}

func (x *ACSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACSMessage.ProtoReflect.Descriptor instead.
func (*ACSMessage) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ACSMessage) GetProposerId() uint64 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

func (x *ACSMessage) GetPayload() isACSMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ACSMessage) GetAgreement() *AgreementMessage {
	if x != nil {
		if x, ok := x.Payload.(*ACSMessage_Agreement); ok {
			return x.Agreement
		}
	}
	return nil
}

func (x *ACSMessage) GetBroadcast() *BroadcastMessage {
	if x != nil {
		if x, ok := x.Payload.(*ACSMessage_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

type isACSMessage_Payload interface {
	isACSMessage_Payload()
}

type ACSMessage_Agreement struct {
	Agreement *AgreementMessage `protobuf:"bytes,2,opt,name=agreement,proto3,oneof"`
}

type ACSMessage_Broadcast struct {
	Broadcast *BroadcastMessage `protobuf:"bytes,3,opt,name=broadcast,proto3,oneof"`
}

func (*ACSMessage_Agreement) isACSMessage_Payload() {}

func (*ACSMessage_Broadcast) isACSMessage_Payload() {}

type AgreementMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgreementMessage_Bval
	//	*AgreementMessage_Aux
	Message       isAgreementMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgreementMessage) Reset() {
	*x = AgreementMessage{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgreementMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreementMessage) ProtoMessage() {}

func (x *AgreementMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreementMessage.ProtoReflect.Descriptor instead.
func (*AgreementMessage) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AgreementMessage) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AgreementMessage) GetMessage() isAgreementMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgreementMessage) GetBval() *BvalRequest {
	if x != nil {
		if x, ok := x.Message.(*AgreementMessage_Bval); ok {
			return x.Bval
		}
	}
	return nil
}

func (x *AgreementMessage) GetAux() *AuxRequest {
	if x != nil {
		if x, ok := x.Message.(*AgreementMessage_Aux); ok {
			return x.Aux
		}
	}
	return nil
}

type isAgreementMessage_Message interface {
	isAgreementMessage_Message()
}

type AgreementMessage_Bval struct {
	Bval *BvalRequest `protobuf:"bytes,2,opt,name=bval,proto3,oneof"`
}

type AgreementMessage_Aux struct {
	Aux *AuxRequest `protobuf:"bytes,3,opt,name=aux,proto3,oneof"`
}

func (*AgreementMessage_Bval) isAgreementMessage_Message() {}

func (*AgreementMessage_Aux) isAgreementMessage_Message() {}

type BvalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BvalRequest) Reset() {
	*x = BvalRequest{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BvalRequest) ProtoMessage() {}

func (x *BvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BvalRequest.ProtoReflect.Descriptor instead.
func (*BvalRequest) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *BvalRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type AuxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuxRequest) Reset() {
	*x = AuxRequest{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxRequest) ProtoMessage() {}

func (x *AuxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxRequest.ProtoReflect.Descriptor instead.
func (*AuxRequest) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *AuxRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type BroadcastMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BroadcastMessage_Proof
	//	*BroadcastMessage_Echo
	//	*BroadcastMessage_Ready
	Payload       isBroadcastMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *BroadcastMessage) GetPayload() isBroadcastMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BroadcastMessage) GetProof() *ProofRequest {
	if x != nil {
		if x, ok := x.Payload.(*BroadcastMessage_Proof); ok {
			return x.Proof
		}
	}
	return nil
}

func (x *BroadcastMessage) GetEcho() *EchoRequest {
	if x != nil {
		if x, ok := x.Payload.(*BroadcastMessage_Echo); ok {
			return x.Echo
		}
	}
	return nil
}

func (x *BroadcastMessage) GetReady() *ReadyRequest {
	if x != nil {
		if x, ok := x.Payload.(*BroadcastMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

type isBroadcastMessage_Payload interface {
	isBroadcastMessage_Payload()
}

type BroadcastMessage_Proof struct {
	Proof *ProofRequest `protobuf:"bytes,1,opt,name=proof,proto3,oneof"`
}

type BroadcastMessage_Echo struct {
	Echo *EchoRequest `protobuf:"bytes,2,opt,name=echo,proto3,oneof"`
}

type BroadcastMessage_Ready struct {
	Ready *ReadyRequest `protobuf:"bytes,3,opt,name=ready,proto3,oneof"`
}

func (*BroadcastMessage_Proof) isBroadcastMessage_Payload() {}

func (*BroadcastMessage_Echo) isBroadcastMessage_Payload() {}

func (*BroadcastMessage_Ready) isBroadcastMessage_Payload() {}

type ProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      []byte                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Proof         [][]byte               `protobuf:"bytes,2,rep,name=proof,proto3" json:"proof,omitempty"`
	Index         uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Leaves        uint64                 `protobuf:"varint,4,opt,name=leaves,proto3" json:"leaves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofRequest) Reset() {
	*x = ProofRequest{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofRequest) ProtoMessage() {}

func (x *ProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofRequest.ProtoReflect.Descriptor instead.
func (*ProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ProofRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *ProofRequest) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ProofRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProofRequest) GetLeaves() uint64 {
	if x != nil {
		return x.Leaves
	}
	return 0
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *ProofRequest          `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *EchoRequest) GetProof() *ProofRequest {
	if x != nil {
		return x.Proof
	}
	return nil
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      []byte                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ReadyRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

type InclusionList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Slot          uint64                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	OperatorId    uint64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Items         []*EncryptedPlaceholder `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionList) Reset() {
	*x = InclusionList{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionList) ProtoMessage() {}

func (x *InclusionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionList.ProtoReflect.Descriptor instead.
func (*InclusionList) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *InclusionList) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *InclusionList) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *InclusionList) GetItems() []*EncryptedPlaceholder {
	if x != nil {
		return x.Items
	}
	return nil
}

type EncryptedPlaceholder struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Hash                  string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Ciphertext            []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Gas                   uint64                 `protobuf:"varint,3,opt,name=gas,proto3" json:"gas,omitempty"`
	EffectiveFeePerGasWei string                 `protobuf:"bytes,4,opt,name=effective_fee_per_gas_wei,json=effectiveFeePerGasWei,proto3" json:"effective_fee_per_gas_wei,omitempty"`
	From                  string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	Nonce                 uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Kind                  string                 `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EncryptedPlaceholder) Reset() {
	*x = EncryptedPlaceholder{}
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedPlaceholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedPlaceholder) ProtoMessage() {}

func (x *EncryptedPlaceholder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bloc_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedPlaceholder.ProtoReflect.Descriptor instead.
func (*EncryptedPlaceholder) Descriptor() ([]byte, []int) {
	return file_proto_bloc_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *EncryptedPlaceholder) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EncryptedPlaceholder) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedPlaceholder) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *EncryptedPlaceholder) GetEffectiveFeePerGasWei() string {
	if x != nil {
		return x.EffectiveFeePerGasWei
	}
	return ""
}

func (x *EncryptedPlaceholder) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EncryptedPlaceholder) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *EncryptedPlaceholder) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_proto_bloc_v1_messages_proto protoreflect.FileDescriptor

const file_proto_bloc_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/bloc/v1/messages.proto\x12\abloc.v1\"\xe9\x01\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x16\n" +
	"\x06direct\x18\x04 \x01(\bR\x06direct\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x12\n" +
	"\x04slot\x18\x06 \x01(\x04R\x04slot\x12(\n" +
	"\x03acs\x18\n" +
	" \x01(\v2\x14.bloc.v1.SlotMessageH\x00R\x03acs\x12*\n" +
	"\x05share\x18\v \x01(\v2\x12.bloc.v1.WireShareH\x00R\x05shareB\t\n" +
	"\apayload\"\x8d\x01\n" +
	"\tWireShare\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x04R\n" +
	"operatorId\x12 \n" +
	"\fbatch_id_hex\x18\x02 \x01(\tR\n" +
	"batchIdHex\x12 \n" +
	"\fsub_batch_id\x18\x03 \x01(\x04R\n" +
	"subBatchId\x12\x1b\n" +
	"\tpoint_hex\x18\x04 \x01(\tR\bpointHex\"P\n" +
	"\vSlotMessage\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12-\n" +
	"\apayload\x18\x02 \x01(\v2\x13.bloc.v1.ACSMessageR\apayload\"\xae\x01\n" +
	"\n" +
	"ACSMessage\x12\x1f\n" +
	"\vproposer_id\x18\x01 \x01(\x04R\n" +
	"proposerId\x129\n" +
	"\tagreement\x18\x02 \x01(\v2\x19.bloc.v1.AgreementMessageH\x00R\tagreement\x129\n" +
	"\tbroadcast\x18\x03 \x01(\v2\x19.bloc.v1.BroadcastMessageH\x00R\tbroadcastB\t\n" +
	"\apayload\"\x88\x01\n" +
	"\x10AgreementMessage\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12*\n" +
	"\x04bval\x18\x02 \x01(\v2\x14.bloc.v1.BvalRequestH\x00R\x04bval\x12'\n" +
	"\x03aux\x18\x03 \x01(\v2\x13.bloc.v1.AuxRequestH\x00R\x03auxB\t\n" +
	"\amessage\"#\n" +
	"\vBvalRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"\"\n" +
	"\n" +
	"AuxRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"\xa7\x01\n" +
	"\x10BroadcastMessage\x12-\n" +
	"\x05proof\x18\x01 \x01(\v2\x15.bloc.v1.ProofRequestH\x00R\x05proof\x12*\n" +
	"\x04echo\x18\x02 \x01(\v2\x14.bloc.v1.EchoRequestH\x00R\x04echo\x12-\n" +
	"\x05ready\x18\x03 \x01(\v2\x15.bloc.v1.ReadyRequestH\x00R\x05readyB\t\n" +
	"\apayload\"o\n" +
	"\fProofRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash\x12\x14\n" +
	"\x05proof\x18\x02 \x03(\fR\x05proof\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x04R\x05index\x12\x16\n" +
	"\x06leaves\x18\x04 \x01(\x04R\x06leaves\":\n" +
	"\vEchoRequest\x12+\n" +
	"\x05proof\x18\x01 \x01(\v2\x15.bloc.v1.ProofRequestR\x05proof\"+\n" +
	"\fReadyRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash\"y\n" +
	"\rInclusionList\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\x123\n" +
	"\x05items\x18\x03 \x03(\v2\x1d.bloc.v1.EncryptedPlaceholderR\x05items\"\xd4\x01\n" +
	"\x14EncryptedPlaceholder\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x10\n" +
	"\x03gas\x18\x03 \x01(\x04R\x03gas\x128\n" +
	"\x19effective_fee_per_gas_wei\x18\x04 \x01(\tR\x15effectiveFeePerGasWei\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kindB\x1eZ\x1cbloc-node/internal/pb/blocv1b\x06proto3"

var (
	file_proto_bloc_v1_messages_proto_rawDescOnce sync.Once
	file_proto_bloc_v1_messages_proto_rawDescData []byte
)

func file_proto_bloc_v1_messages_proto_rawDescGZIP() []byte {
	file_proto_bloc_v1_messages_proto_rawDescOnce.Do(func() {
		file_proto_bloc_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bloc_v1_messages_proto_rawDesc), len(file_proto_bloc_v1_messages_proto_rawDesc)))
	})
	return file_proto_bloc_v1_messages_proto_rawDescData
}

var file_proto_bloc_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_bloc_v1_messages_proto_goTypes = []any{
	(*Envelope)(nil),             // 0: bloc.v1.Envelope
	(*WireShare)(nil),            // 1: bloc.v1.WireShare
	(*SlotMessage)(nil),          // 2: bloc.v1.SlotMessage
	(*ACSMessage)(nil),           // 3: bloc.v1.ACSMessage
	(*AgreementMessage)(nil),     // 4: bloc.v1.AgreementMessage
	(*BvalRequest)(nil),          // 5: bloc.v1.BvalRequest
	(*AuxRequest)(nil),           // 6: bloc.v1.AuxRequest
	(*BroadcastMessage)(nil),     // 7: bloc.v1.BroadcastMessage
	(*ProofRequest)(nil),         // 8: bloc.v1.ProofRequest
	(*EchoRequest)(nil),          // 9: bloc.v1.EchoRequest
	(*ReadyRequest)(nil),         // 10: bloc.v1.ReadyRequest
	(*InclusionList)(nil),        // 11: bloc.v1.InclusionList
	(*EncryptedPlaceholder)(nil), // 12: bloc.v1.EncryptedPlaceholder
}
var file_proto_bloc_v1_messages_proto_depIdxs = []int32{
	2,  // 0: bloc.v1.Envelope.acs:type_name -> bloc.v1.SlotMessage
	1,  // 1: bloc.v1.Envelope.share:type_name -> bloc.v1.WireShare
	3,  // 2: bloc.v1.SlotMessage.payload:type_name -> bloc.v1.ACSMessage
	4,  // 3: bloc.v1.ACSMessage.agreement:type_name -> bloc.v1.AgreementMessage
	7,  // 4: bloc.v1.ACSMessage.broadcast:type_name -> bloc.v1.BroadcastMessage
	5,  // 5: bloc.v1.AgreementMessage.bval:type_name -> bloc.v1.BvalRequest
	6,  // 6: bloc.v1.AgreementMessage.aux:type_name -> bloc.v1.AuxRequest
	8,  // 7: bloc.v1.BroadcastMessage.proof:type_name -> bloc.v1.ProofRequest
	9,  // 8: bloc.v1.BroadcastMessage.echo:type_name -> bloc.v1.EchoRequest
	10, // 9: bloc.v1.BroadcastMessage.ready:type_name -> bloc.v1.ReadyRequest
	8,  // 10: bloc.v1.EchoRequest.proof:type_name -> bloc.v1.ProofRequest
	12, // 11: bloc.v1.InclusionList.items:type_name -> bloc.v1.EncryptedPlaceholder
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_bloc_v1_messages_proto_init() }
func file_proto_bloc_v1_messages_proto_init() {
	if File_proto_bloc_v1_messages_proto != nil {
		return
	}
	file_proto_bloc_v1_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Acs)(nil),
		(*Envelope_Share)(nil),
	}
	file_proto_bloc_v1_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*ACSMessage_Agreement)(nil),
		(*ACSMessage_Broadcast)(nil),
	}
	file_proto_bloc_v1_messages_proto_msgTypes[4].OneofWrappers = []any{
		(*AgreementMessage_Bval)(nil),
		(*AgreementMessage_Aux)(nil),
	}
	file_proto_bloc_v1_messages_proto_msgTypes[7].OneofWrappers = []any{
		(*BroadcastMessage_Proof)(nil),
		(*BroadcastMessage_Echo)(nil),
		(*BroadcastMessage_Ready)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bloc_v1_messages_proto_rawDesc), len(file_proto_bloc_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bloc_v1_messages_proto_goTypes,
		DependencyIndexes: file_proto_bloc_v1_messages_proto_depIdxs,
		MessageInfos:      file_proto_bloc_v1_messages_proto_msgTypes,
	}.Build()
	File_proto_bloc_v1_messages_proto = out.File
	file_proto_bloc_v1_messages_proto_goTypes = nil
	file_proto_bloc_v1_messages_proto_depIdxs = nil
}
